### ISSUE TITLE
Default Event on creating of User

### ISSUE THREAD

**Issue by bonnieli** [hatchways/team-matcha#36]
on Creation of user, create an initial Meeting for a 60 min duration (this is default)

**Comment by brian-e-haley** [comment]
@Kcheung42 @gerardopar can we consider this issue closed?

**Comment by gerardopar** [comment]
> @Kcheung42 @gerardopar can we consider this issue closed?

Yeah, since we technically create that first event as a default

**Comment by brian-e-haley** [comment]
We will consider this issue closed then.
